# welcome.conf on Debian, penguins-eggs 26.3.21
---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true
requirements:
  requiredStorage: 10
  requiredRam: 1
  check:
    - storage
    - ram
    - power
    - root
  required:
    - storage
    - ram
    - root
