# settings.conf Universale (Gestito da COA)
---
modules-search:
  - local

oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false

# Definiamo DUE istanza symlink e finalize
instances:
  - id:       oa_finalize
    module:   shellprocess
    config:   shellprocess_oa_finalize.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition       # Crea le partizioni fisiche
      - mount           # Le monta in /tmp/calamares-root
      - unpackfs        # Scompatta il tuo filesystem.squashfs
      - machineid       # Genera un nuovo /etc/machine-id
      - fstab           # Crea l'fstab con i nuovi UUID
      - locale          # Imposta la lingua base
      - keyboard        # Imposta la tastiera
      - localecfg       # Applica la localizzazione (se supportato)
      - users           # Crea l'utente senza controlli password fastidiosi
      - shellprocess@oa_finalize # <--- IL NOSTRO CAVALLO DI TROIA (OA fa bootloader e initramfs!)
      - umount          # Smonta tutto a lavoro finito
  - show:
      - finished

branding: eggs
prompt-install: false
dont-chroot: false