/*
 * src/actions/install_uefi.c
 * Remastering core: GRUB installation on physical hardware (Krill)
 * oa: eggs in my dialect🥚🥚
 *
 * Author: Piero Proietti <piero.proietti@gmail.com>
 * License: GPL-3.0-or-later
 */
#include "oa.h"

static void get_partition_path(const char *disk, int part_num, char *out_path, size_t max_len) {
    if (strstr(disk, "nvme") || strstr(disk, "mmcblk") || strstr(disk, "loop")) {
        snprintf(out_path, max_len, "%sp%d", disk, part_num);
    } else {
        snprintf(out_path, max_len, "%s%d", disk, part_num);
    }
}

static int get_uuid(const char *device, char *uuid_out, size_t max_len) {
    char cmd[CMD_MAX];
    snprintf(cmd, sizeof(cmd), "blkid -s UUID -o value %s", device);
    
    FILE *fp = popen(cmd, "r");
    if (!fp) return -1;
    if (fgets(uuid_out, max_len, fp) != NULL) {
        uuid_out[strcspn(uuid_out, "\n")] = 0;
    }
    pclose(fp);
    return 0;
}

int install_fstab(OA_Context *ctx) {
    cJSON *pathLiveFs = cJSON_GetObjectItemCaseSensitive(ctx->root, "pathLiveFs");
    cJSON *disk_node = cJSON_GetObjectItemCaseSensitive(ctx->task, "run_command");
    if (!cJSON_IsString(pathLiveFs) || !cJSON_IsString(disk_node)) return 1;

    const char *disk = disk_node->valuestring;
    char efi_part[128], root_part[128];
    char efi_uuid[128] = {0}, root_uuid[128] = {0};

    // AGGIORNATO: EFI è la 2, ROOT è la 3
    get_partition_path(disk, 2, efi_part, sizeof(efi_part));
    get_partition_path(disk, 3, root_part, sizeof(root_part));
    printf("\033[1;34m[oa FSTAB]\033[0m Generating fstab for disk %s...\n", disk);

    get_uuid(efi_part, efi_uuid, sizeof(efi_uuid));
    get_uuid(root_part, root_uuid, sizeof(root_uuid));

    char fstab_path[PATH_SAFE];
    snprintf(fstab_path, sizeof(fstab_path), "%s/liveroot/etc/fstab", pathLiveFs->valuestring);
    FILE *f = fopen(fstab_path, "w");
    if (!f) return 1;

    fprintf(f, "# /etc/fstab: static file system information. Generated by coa/oa.\n");
    fprintf(f, "# <file system> <mount point>   <type>  <options>       <dump>  <pass>\n\n");
    fprintf(f, "UUID=%s /               ext4    errors=remount-ro 0       1\n", root_uuid);
    fprintf(f, "UUID=%s /boot/efi       vfat    umask=0077      0       1\n", efi_uuid);
    fclose(f);
    
    printf("\033[1;32m[oa FSTAB]\033[0m Successfully wrote UUIDs to %s\n", fstab_path);
    return 0;
}